workspace:
  base: /go
  path: src/uct


pipeline:
  core:
    image: golang:1.7
    environment:
      - GOPATH=/go
    commands:
      - cd /go/src/uct
      - export PATH=$PATH:$GOPATH/bin
      - wget -q https://github.com/Masterminds/glide/releases/download/v0.12.1/glide-v0.12.1-linux-amd64.tar.gz
      - tar -xzf glide-v0.12.1-linux-amd64.tar.gz
      - mv linux-amd64/glide /usr/bin
      - glide install
      - export PATH=$PATH:$GOPATH/bin
      - go install -v uct/ein
      - go install -v uct/hermes
      - go install -v uct/scrapers/rutgers
      - go install -v uct/servers/spike

  image:
    image: docker
    commands:
      - cd /go/src/uct
      - docker build -t tevjef/uct-core:ci-ein -f Dockerfile-ein .
      - docker build -t tevjef/uct-core:ci-spike -f Dockerfile-spike .
      - docker build -t tevjef/uct-core:ci-hermes -f Dockerfile-hermes .
      - docker build -t tevjef/uct-core:ci-rutgers-cm -f Dockerfile-rutgers-cm .
      - docker build -t tevjef/uct-core:ci-rutgers-nb -f Dockerfile-rutgers-nb .
      - docker build -t tevjef/uct-core:ci-rutgers-nk -f Dockerfile-rutgers-nk .
      - docker build -t tevjef/uct-core:ci-fluentd -f support/fluentd/Dockerfile support/fluentd
      - docker build -t tevjef/uct-core:ci-fluentd-gen -f support/fluentd/Dockerfile support/fluentd/gen
      - docker build -t tevjef/uct-core:ci-nginx -f support/nginx/Dockerfile support/nginx
      - docker build -t tevjef/uct-core:ci-nginx-gen -f support/nginx/Dockerfile support/nginx/gen
      - docker build -t tevjef/uct-core:ci-postgresql -f support/postgresql/Dockerfile support/postgresql
      - docker build -t tevjef/uct-core:ci-telegraf -f support/telegraf/Dockerfile support/telegraf

  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: ci
    username: drone