workspace:
  base: /go
  path: src/github.com/tevjef/uct


pipeline:
  compile:
    image: golang:1.7
    environment:
      - GOPATH=/go
    commands:
      - cd /go/src/uct
      - export PATH=$PATH:$GOPATH/bin
      - wget -q https://github.com/Masterminds/glide/releases/download/v0.12.1/glide-v0.12.1-linux-amd64.tar.gz
      - tar -xzf glide-v0.12.1-linux-amd64.tar.gz
      - mv linux-amd64/glide /usr/bin
      - glide install
      - export PATH=$PATH:$GOPATH/bin
      - go install -v uct/$$CORE
  slack:
    webhook_url: https://hooks.slack.com/services/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
    channel: ci
    username: drone

matrix:
  CORE:
   - ein
   - hermes
   - scrapers/rutgers
   - servers/spike