version: '2'
services:
  blog:
    image: tevjef/alpine-ghost
    restart: on-failure:3
    volumes:
      - '/var/lib/ghost:/var/lib/ghost'
    environment:
      - NODE_ENV=production
      - GHOST_DOMAIN=https://blog.${BASE_URL}/
      - GHOST_PROD_FORCE_ADMIN_SSL=true
      - VIRTUAL_HOST=blog.${BASE_URL}
      - LETSENCRYPT_HOST=blog.${BASE_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.blog"
    labels:
      fluentd.tag: "blog"

  postgresql:
    image: tevjef/uct-core:staging-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/uct/uct/postgresql:/var/lib/postgresql
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.postgresql"
    labels:
      fluentd.tag: "postgresql"

  ein:
    image: 'tevjef/uct-core:staging-ein'
    links:
      - postgresql
      - redis
      - influxdb
    restart: on-failure:3
    ports:
      - '13100'
    depends_on:
      - fluentd
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: "docker.core.ein"
    labels:
      fluentd.tag: "core.ein"
      fluentd.influxdb.precision: "s"
      fluentd.influxdb.tags: "[\"university_name\"]"

  grafana:
    image: grafana/grafana
    restart: on-failure:3
    links:
      - influxdb
    volumes:
      - /var/lib/uct/grafana:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_SERVER_ROOT_URL=https://grafana.${BASE_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - VIRTUAL_HOST=grafana.${BASE_URL}
      - LETSENCRYPT_HOST=grafana.${BASE_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.grafana"
    labels:
      fluentd.tag: "grafana"

  hermes:
    image: tevjef/uct-core:staging-hermes
    restart: on-failure:3
    ports:
      - '13200:13200'
    depends_on:
      - postgresql
      - influxdb
      - fluentd
    links:
      - postgresql
      - influxdb
    environment:
      - FCM_API_KEY=${FCM_API_KEY}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    logging:
      driver: fluentd
      options:
        tag: "docker.core.hermes"
    labels:
      fluentd.tag: "core.hermes"
      fluentd.influxdb.precision: "ms"
      fluentd.influxdb.tags: "[\"status\", \"university_name\"]"

  influxdb:
    image: tevjef/influxdb
    restart: unless-stopped
    volumes:
      - /var/lib/uct/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083"
    environment:
      - VIRTUAL_PORT=8083
      - VIRTUAL_HOST=influxdb.${BASE_URL}
      - INFLUXDB_CREATE_DB=system;universityct
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.influxdb"
    labels:
      fluentd.tag: "influxdb"

  nginx:
    container_name: nginx
    image: tevjef/uct-core:staging-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/conf.d
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.nginx"
    labels:
      fluentd.tag: "nginx"
      fluentd.influxdb.precision: "s"
      fluentd.influxdb.tags: "[\"host\", \"status\"]"

  nginx-gen:
    image: tevjef/uct-core:staging-nginx-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: fluentd
      options:
        tag: "docker.nginx-gen"
    labels:
      fluentd.tag: "nginx-gen"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.letsencrypt"
    labels:
      fluentd.tag: "letsencrypt"

  redis:
    image: redis:alpine
    restart: always
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "docker.redis"
    labels:
      fluentd.tag: "redis"

  rutgers-cm:
    image: tevjef/uct-core:staging-rutgers-cm
    restart: on-failure:3
    ports:
      - '13302'
    depends_on:
      - redis
      - influxdb
      - fluentd
    links:
      - redis
      - influxdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: "docker.core.rutgers-cm"
    labels:
      fluentd.tag: "core.rutgers-cm"
      fluentd.influxdb.tags: "[\"scraper_name\"]"

  rutgers-nb:
    image: tevjef/uct-core:staging-rutgers-nb
    restart: on-failure:3
    ports:
      - '13303'
    depends_on:
      - redis
      - influxdb
      - fluentd
    links:
      - redis
      - influxdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: "docker.core.rutgers-nb"
    labels:
      fluentd.tag: "core.rutgers-nb"
      fluentd.influxdb.tags: "[\"scraper_name\"]"

  rutgers-nk:
    image: tevjef/uct-core:staging-rutgers-nk
    restart: on-failure:3
    ports:
      - '13301'
    depends_on:
      - redis
      - influxdb
      - fluentd
    links:
      - redis
      - influxdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: "docker.core.rutgers-nk"
    labels:
      fluentd.tag: "core.rutgers-nk"
      fluentd.influxdb.tags: "[\"scraper_name\"]"

  spike:
    restart: on-failure:3
    depends_on:
      - postgresql
      - redis
      - influxdb
      - fluentd
    image: tevjef/uct-core:staging-spike
    links:
      - postgresql
      - redis
      - influxdb
    ports:
      - '13400'
    environment:
      - GIN_MODE=release
      - VIRTUAL_HOST=api.${BASE_URL}
      - VIRTUAL_PORT=9876
      - LETSENCRYPT_HOST=api.${BASE_URL}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    logging:
      driver: fluentd
      options:
        tag: "docker.core.spike"
    labels:
      fluentd.tag: "core.spike"
      fluentd.influxdb.precision: "ms"
      fluentd.influxdb.tags: "[\"university_name\", \"user-agent\", \"method\", \"status\"]"

  telegraf:
    image: tevjef/uct-core:staging-telegraf
    links:
      - postgresql
      - redis
      - influxdb
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/var/run/utmp:/var/run/utmp:ro'
    logging:
      driver: fluentd
      options:
        tag: "docker.telegraf"
    labels:
      fluentd.tag: "telegraf"
    environment:
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - RESPONSE_ENDPOINT=https://api.${BASE_URL}/v2/universities
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_DATABASE=system
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
  fluentd:
    container_name: fluentd
    image: tevjef/uct-core:staging-fluentd
    ports:
      - '24224:24224'
    volumes_from:
      - fluentd-gen

  fluentd-gen:
    container_name: fluentd-gen
    image: tevjef/uct-core:staging-fluentd-gen
    command: -notify-sighup fluentd -wait 2s -watch /etc/docker-gen/templates/fluent.conf.tmpl /fluentd/etc/fluent.conf
    volumes:
      - /fluentd/etc
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_DATABASE=universityct
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

networks:
  default:
    external:
      name: uct_default