version: '2'
services:
  fluentd:
    container_name: fluentd
    image: tevjef/uct-core:staging-fluentd
    ports:
      - '24224:24224'
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes_from:
      - dockergen

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup fluentd -wait 5 -watch /etc/docker-gen/templates/fluent.conf.tmpl /fluentd/etc/fluent.conf
    volumes:
      - /fluentd/etc
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./fluent.conf.tmpl:/etc/docker-gen/templates/fluent.conf.tmpl

networks:
  default:
    external:
      name: uct_default


